### PR TITLE
Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #7

### CODE REVIEW

**Comment by jakirkham** [comment]
The compiler error message is not very clear, but this is a bug in their code that the compiler caught.

`PyList_SET_ITEM` returns `void`, but they are treating `PyList_SET_ITEM` as if it returned an error code, which it does not. Either the check should be dropped or it can be patched to use `PyList_SetItem`, which does return an error code (`int`) that can be checked.

Would also raise this issue with upstream so they are aware of this bug.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by Anthchirp** [comment]
We have a 3.7 build now

**Pull request closed without merging**
